--- pyproject.toml.orig	2025-09-10 08:41:47 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=77", "setuptools-scm>=8"]
+requires = ["setuptools>=63", "setuptools-scm>=8"]
 build-backend = "setuptools.build_meta"
 
 [project]
